/* islands — user-facing strings (es-MX).
 *
 * Single source of truth for every string shown to the user. Keys referenced
 * from the schema (setting.*) and the settings UI (ui.*).
 */

export const STRINGS = Object.freeze({
  // ---- setting labels (one per schema entry) -----------------------------
  "setting.system.enabled": "Activar diseño islands",
  "setting.layout.variant": "Variante",
  "setting.layout.gap": "Separación",
  "setting.layout.bar-height": "Altura de la barra",
  "setting.layout.window-radius": "Radio de ventana",
  "setting.layout.notch-width": "Ancho del notch",
  "setting.layout.tabs-layout": "Posición de pestañas",
  "setting.frame.enabled": "Marco de contenido",
  "setting.frame.border": "Borde del marco",
  "setting.frame.radius-override": "Radio del marco",
  "setting.urlbar.host-only": "Mostrar solo el dominio",
  "setting.urlbar.spotlight": "Modo spotlight",
  "setting.urlbar.spotlight-width": "Ancho del spotlight",
  "setting.tabs.favicon-only-threshold": "Pestañas solo favicon",
  "setting.tabs.min-width": "Ancho mínimo de pestaña",
  "setting.tabs.close-on-hover": "Cerrar al pasar el cursor",
  "setting.tabs.active-accent": "Acento en pestaña activa",
  "setting.motion.enabled": "Activar animaciones",
  "setting.motion.speed": "Velocidad",
  "setting.motion.spring-stiffness": "Rigidez del resorte",
  "setting.motion.spring-damping": "Amortiguación del resorte",
  "setting.motion.respect-reduced-motion": "Respetar movimiento reducido",
  "setting.notch.loading": "Progreso de carga",
  "setting.notch.downloads": "Descargas activas",
  "setting.notch.media": "Reproducción de audio",
  "setting.colors.source": "Fuente de colores",
  "setting.colors.palette-file": "Archivo de paleta",
  "setting.colors.accent": "Color de acento",
  "setting.colors.private-tint": "Tinte de ventana privada",
  "setting.colors.blur": "Desenfoque de fondo",
  "setting.behavior.safari-merge": "Fusión experimental con pestañas",
  "setting.presets.current": "Preset actual",

  // ---- enum option labels --------------------------------------------------
  "opt.variant.islands": "Islas",
  "opt.variant.notch": "Notch",
  "opt.tabs-layout.horizontal": "Horizontales",
  "opt.tabs-layout.vertical": "Verticales (nativo)",
  "opt.colors.source.theme": "Tema de Firefox",
  "opt.colors.source.manual": "Manual",
  "opt.colors.source.file": "Archivo de paleta",

  // ---- group titles ---------------------------------------------------------
  "group.system": "Sistema",
  "group.layout": "Diseño",
  "group.frame": "Marco de contenido",
  "group.urlbar": "Barra de direcciones",
  "group.tabs": "Pestañas",
  "group.motion": "Movimiento",
  "group.dynamicNotch": "Notch dinámico",
  "group.colors": "Colores",
  "group.behavior": "Comportamiento",
  "group.presets": "Presets",
  "group.diagnostics": "Diagnóstico",

  // ---- quick panel -----------------------------------------------------------
  "quick.title": "islands",
  "quick.animations": "Animaciones",
  "quick.open-settings": "Abrir configuración completa",
  "quick.close": "Cerrar",
  "quick.unavailable": "La configuración no está disponible en esta ventana.",

  // ---- full settings page ------------------------------------------------------
  "settings.title": "Configuración de islands",
  "settings.subtitle": "Diseño estilo Safari para Firefox — cambios en vivo, sin reiniciar.",
  "settings.diagnostics.version": "Versión de Firefox",
  "settings.diagnostics.nova": "Nova activo",
  "settings.diagnostics.loader": "Cargador",
  "settings.diagnostics.selector-health": "Salud de selectores",
  "settings.diagnostics.ok": "Todo presente",
  "settings.diagnostics.missing": "Faltan:",
  "settings.diagnostics.kill-switch": "Interruptor general",
  "settings.diagnostics.open-quick-panel": "El panel rápido y esta página aplican cambios en vivo.",
  "settings.presets.save": "Guardar preset",
  "settings.presets.load": "Cargar preset",
  "settings.presets.export": "Exportar JSON",
  "settings.presets.import": "Importar JSON",
  "settings.presets.reset": "Restablecer todo",
  "settings.presets.saved": "Preset guardado.",
  "settings.presets.loaded": "Preset cargado.",
  "settings.presets.exported": "Exportado.",
  "settings.presets.imported": "Importado.",
  "settings.presets.reset-done": "Todo restablecido.",
  "settings.presets.invalid": "El archivo JSON no es un preset válido.",
  "settings.presets.confirm-reset": "¿Restablecer todas las opciones a sus valores iniciales?",
  "settings.footer": "Los valores se aplican al instante y se guardan en tus preferencias.",
});