#+author: HBlanqueto
#+date:   2022-03-10
#+EMAIL:  humbertoblanqueto@outlook.com
#+DESCRIPTION: This document has the documentation and explanation of my dotfiles
#+KEYWORDS:  nixos, nix, zfs, wayland, dotfiles
#+LANGUAGE:  en

#+HTML:<div align=center>
* Nixdots
#+HTML:</div>

*Where am I? Who are you?*

#+HTML:<a href="https://nixos.org/"><img alt="NixOS Logo" height="150" align="right" src="https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg"></a>

Hello Stranger! These files are my personal NixOS settings thought for any computer. By default I like using Gnome (Wayland) & Pipewire; importance of mentioning It's due to most part of my files depend on them. That's why during the installation you must modify =configuration.nix= & =hardware-configuration.nix= in accordance with your hardware. Oh yeah, I'm concerned about what [[https://nixos.wiki/wiki/Flakes#:~:text=Nix%20flakes%20is%20some%20upcoming%20feature%20in%20the,flake.nix%20where%20they%20can%20describe%20their%20own%20dependencies.][flakes]] are, I want to implement it on my dotfiles but I don't comprehend at all. 

** Table of contents :TOC_3_gh:QUOTE:
#+BEGIN_QUOTE
- [[#nixdots][Nixdots]]
  - [[#setup-for-nixos][Setup for NixOS]]
    - [[#zfs-partitions-][ZFS Partitions]]
    - [[#installing-the-system-%EF%B8%8F][Installing the System]]
    - [[#unstable-channel-%EF%B8%8F][Unstable Channel]]
  - [[#gallery][Gallery]]
  - [[#special-thanks][Special Thanks]]
#+END_QUOTE

** Setup for NixOS

- Get the latest [[https://nixos.org/download.html#nixos-iso][ISO]] and boot into the enviroment. I'd recommend any ISO with a GUI.
- If you plan using ZFS for your whole disk, be careful and follow the next steps:

*** ZFS Partitions 💽

I took as a reference this [[https://cheat.readthedocs.io/en/latest/nixos/zfs_install.html][Dan's Cheat Sheets]] to take the leap on this filesystem as a personal experiment. Don't come to the Dark Side.

#+begin_src sh

# Create 2 partitions.
cfdisk /dev/sda

# Prepare ZFS on /dev/sdaX. "X" could be changed to another number.
zpool create -f -O mountpoint=none \ 
-O atime=off \ 
-O compression=zstd \
-O xattr=sa \ 
-O acltype=posixacl \
-o ashift=12 \
-R /mnt \
rpool /dev/sdaX

# Create /root & /home subvolumes.
zfs create -o mountpoint=none rpool/root
zfs create -o mountpoint=legacy rpool/root/nixos
zfs create -o mountpoint=legacy rpool/home

# Mount the /root and /home.
mount -t zfs rpool/root/nixos /mnt
mkdir /mnt/home
mount -t zfs rpool/home /mnt/home

# Create and mount /boot.
mkfs.vfat /dev/sdaX
mkdir /mnt/boot
mount /dev/sdaX /mnt/boot

#+end_src

*** Installing the System ❄️

#+begin_src sh

# Generate initial configuration.
nixos-generate-config --root /mnt

# Copy the hardware-configuration.nix file to ~/
# This is totally necesary for the next steps.
cp /mnt/etc/nixos/hardware-configuration.nix ~/

# # Get into a Nix shell with git.
nix-shell -p git

# Clone the repository & copy the files.
# Remember to change modules and drivers relative to hardaware's file you have in ~/
git clone https://github.com/HBlanqueto/nixdots.git --depth 1
cp -r ~/nixdots/nixos /mnt/etc/

# Once you modified the files. Install the OS.
nixos-install --root /mnt
#+end_src

*** Unstable Channel ☃️

Upgrading NixOS to Unstable version, It's easy as the next steps here.

#+begin_src sh
# Not using sudo only affects users (user packages).
nix-channel --add https://nixos.org/channels/nixos-unstable nixos

# Update the channel.
nix-channel --update

# Rebuild the system.
nixos-rebuild switch --upgrade
#+end_src

** Gallery

#+HTML:<img alt="Screenshot" align="center" src="https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg"></a>

#+HTML:<img alt="Screenshot" align="center" src="https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg"></a>

** Special Thanks
- [[https://github.com/JavaCafe01/dotfiles][dotfiles]] by *javacafe01*
- [[https://github.com/Leznom/VitalConfig][VitalConfig]] by *Leznom*
- [[https://github.com/jx11r/nixdots][nixdots]] by *jx11r*