#+author: HBlanqueto
#+date:   2022-03-10
#+EMAIL:  humbertoblanqueto@outlook.com
#+DESCRIPTION: This document has the documentation and explanation of my dotfiles
#+KEYWORDS:  nixos, nix, zfs, wayland, dotfiles
#+LANGUAGE:  en

#+HTML:<div align=center>
* Nixdots
#+HTML:</div>

*What the hell is this?*

#+HTML:<a href="https://nixos.org/"><img alt="NixOS Logo" height="150"  align="right" src="https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg"></a>

Hello Peter! I like ricing on r/unixporn and meaby you're looking for this dots. Here you will find my base NixOS system configuration for my day-to-day, these files are thought for easy and compatible uses for my =HP-23-q025la= and have been thought to be managed by Nix. By default I'm using gnome, wayland, pipewire and zfs, this is important to mention beacause most part of the files depends on them. Oh yeah, I want to understand what [[https://nixos.wiki/wiki/Flakes#:~:text=Nix%20flakes%20is%20some%20upcoming%20feature%20in%20the,flake.nix%20where%20they%20can%20describe%20their%20own%20dependencies.][flakes]] are. 

** Table of contents :TOC_3_gh:QUOTE:
#+BEGIN_QUOTE
- [[#nixdots][Nixdots]]
  - [[#setup-for-nixos][Setup for NixOS]]
    - [[#zfs-partitions-][ZFS Partitions]]
    - [[#installing-the-system-%EF%B8%8F][Installing the System]]
    - [[#unstable-channel-%EF%B8%8F][Unstable Channel]]
  - [[#special-thanks][Special Thanks]]
#+END_QUOTE

** Setup for NixOS

- Get the latest [[https://nixos.org/download.html#nixos-iso][ISO]] and boot into the enviroment.
- If you plan using ZFS for your whole disk, be careful and read an article

*** ZFS Partitions 💽

I had to base on Arch Linux wiki's and this [[https://cheat.readthedocs.io/en/latest/nixos/zfs_install.html][tutorial]] to make my partitions in this way. I decided moving to this filesystem as a personal experiment, I won't recommend you to try this if you're new on linux. 

#+begin_src sh

# Create your partitions. For this you'll only need two of them.
cfdisk /dev/sda

# Prepare ZFS on /dev/sda7. It could be changed to another number
# I'm explaining this part for my dual boot.
# More information on: https://wiki.archlinux.org/title/Install_Arch_Linux_on_ZFS
zpool create -f -O mountpoint=none \ 
-O atime=off \ 
-O compression=zstd \ 
-O xattr=sa \ 
-O acltype=posixacl \
-o ashift=12 \
-R /mnt \
rpool /dev/sda7

# Create the filesystems. This layout is designed so that /home is separate from the root.
zfs create -o mountpoint=none rpool/root
zfs create -o mountpoint=legacy rpool/root/nixos
zfs create -o mountpoint=legacy rpool/home

# Mount the root and home.
mount -t zfs rpool/root/nixos /mnt
mkdir /mnt/home
mount -t zfs rpool/home /mnt/home

# Create and mount /boot. In my case I'd use /dev/sda6
mkfs.vfat /dev/sda6
mkdir /mnt/boot
mount /dev/sda6 /mnt/boot

#+end_src

*** Installing the System ❄️

In the case you didn't decide to use the previous steps you'll have to regenerate =hardware-configuration.nix= and configure the bootloader and any other thing my file has. 

#+begin_src sh
# Get git. 
nix-shell -p git

# Clone the repository & copy the files.
git clone https://github.com/HBlanqueto/nixdots.git --depth 1
cp ~/nixdots/nixos /mnt/etc/

# Install NixOS
nixos-install --root /mnt
#+end_src

*** Unstable Channel ☃️

I like using the 22.05 version of the system, activate unstable on NixOS is as easier as following the next commands with sudo:

#+begin_src sh
# Not using sudo only affects users (user packages).
nix-channel --add https://nixos.org/channels/nixos-unstable nixos

# Update the channel.
nix-channel --update

# Rebuild the system.
nixos-rebuild switch --upgrade
#+end_src

** Special Thanks
- [[https://github.com/JavaCafe01/dotfiles][dotfiles]] by *javacafe01*
- [[https://github.com/Leznom/VitalConfig][VitalConfig]] by *Leznom*
- [[https://github.com/jx11r/nixdots][nixdots]] by *jx11r*
