#+HTML:<div align=center>

* Nixdots
Welcome, my =$HOME= is your =$HOME=

#+HTML:</div>

*What is this?*


#+HTML:<a href="https://nixos.org/"><img alt="NixOS Logo" height="150"  align="right" src="https://github.com/NixOS/nixos-artwork/blob/master/logo/nix-snowflake.svg"></a>

こんにちは、ようこそ! This is my special repository, which you'll find several of my configurations that I use in my day-to-day life on my NixOS system. You probably come for the themes and for any rice that I uploaded to r/unixporn, well feel free to use my files. My main goal is to get to use it perfectly and understand [[https://nixos.wiki/wiki/Flakes#:~:text=Nix%20flakes%20is%20some%20upcoming%20feature%20in%20the,flake.nix%20where%20they%20can%20describe%20their%20own%20dependencies.][flakes]]. 

I am a newbie using this system, the configuration of my nix files is for a =HP 23-q025la= computer. Use my settings as a template at your own risk.

** Table of contents :TOC_3_gh:QUOTE:
#+BEGIN_QUOTE
- [[#nixdots][Nixdots]]
  - [[#why-nixos][Why NixOS?]]
  - [[#setup][Setup]]
    - [[#install-nixos][Install NixOS]]
    - [[#nixos-unstable][NixOS Unstable]]
  - [[#special-thanks][Special Thanks]]
#+END_QUOTE

** Why NixOS?
Nix is a powerful package manager for Linux and other Unix systems that makes package management reliable and reproducible. One of the reasons why I like it the most is because of the fact that it makes my dotfiles with its nix files as well as being able to quickly make backups of everything.

=Ah, yeah. Also I'm masoquist.=

** Setup

*** Install NixOS
- Get the [[https://nixos.org/download.html#nixos-iso][ISO]] and boot into the enviroment.
- Mount the system and make the partitions. Also generate the basic configuration. 
- Follow these commands:
#+begin_src markdown
# Get git.
nix-shell -p git

# Clone the repository.
git clone https://github.com/HBlanqueto/nixdots.git --depth 1
cp ~/nixdots/nixos /mnt/etc/

# Generate the hardware configuration according your hardware
rm -rf /mnt/etc/nixos/hardware-configuration.nix
nixos-generate-config --root /mnt

# Install NixOS
nixos-install --root /mnt
#+end_src

- Add the root password, reboot the system.
- Log in as your normal user & enjoy the system.

*** NixOS Unstable
Already you are in your system, If you're interested in using NixOS Unstable, the way to use It'll be: 
#+begin_src markdown
# Execute this commands in root. 
nix-channel --add https://nixos.org/channels/nixos-unstable nixos
nix-channel --update
nixos-rebuild switch --upgrade
#+end_src

** Special Thanks
- [[https://github.com/JavaCafe01/dotfiles][dotfiles]] by *javacafe01*
- [[https://github.com/Leznom/VitalConfig][VitalConfig]] by *Leznom*
