let
    theme = import ../../../../share/themes;
in

rec {
    globs = [ ];

    dirs = [
        { name = ".config"; text = ""; fg = "blue"; }
        { name = ".git"; text = ""; fg = "blue"; }
        { name = ".github"; text = ""; fg = "blue"; }
        { name = ".npm"; text = ""; fg = "blue"; }
        { name = "Desktop"; text = ""; fg = "blue"; }
        { name = "Development"; text = ""; fg = "blue"; }
        { name = "Documents"; text = ""; fg = "blue"; }
        { name = "Downloads"; text = ""; fg = "blue"; }
        { name = "Library"; text = ""; fg = "blue"; }
        { name = "Movies"; text = ""; fg = "blue"; }
        { name = "Music"; text = ""; fg = "blue"; }
        { name = "Pictures"; text = ""; fg = "blue"; }
        { name = "Public"; text = ""; fg = "blue"; }
        { name = "Videos"; text = ""; fg = "blue"; }
    ];

    files = [
        { name = ".babelrc"; text = ""; fg = "yellow"; }
        { name = ".bash_profile"; text = ""; fg = "green"; }
        { name = ".bashrc"; text = ""; fg = "green"; }
        { name = ".clang-format"; text = ""; fg = "cyan"; }
        { name = ".clang-tidy"; text = ""; fg = "cyan"; }
        { name = ".codespellrc"; text = "󰓆"; fg = "lightred"; }
        { name = ".condarc"; text = ""; fg = "green"; }
        { name = ".dockerignore"; text = "󰡨"; fg = "blue"; }
        { name = ".ds_store"; text = ""; fg = "gray"; }
        { name = ".editorconfig"; text = ""; fg = "yellow"; }
        { name = ".env"; text = ""; fg = "yellow"; }
        { name = ".eslintignore"; text = ""; fg = "magenta"; }
        { name = ".eslintrc"; text = ""; fg = "magenta"; }
        { name = ".git-blame-ignore-revs"; text = ""; fg = "red"; }
        { name = ".gitattributes"; text = ""; fg = "red"; }
        { name = ".gitconfig"; text = ""; fg = "red"; }
        { name = ".gitignore"; text = ""; fg = "red"; }
        { name = ".gitlab-ci.yml"; text = ""; fg = "lightred"; }
        { name = ".gitmodules"; text = ""; fg = "red"; }
        { name = ".gtkrc-2.0"; text = ""; fg = "green"; }
        { name = ".gvimrc"; text = ""; fg = "green"; }
        { name = ".justfile"; text = ""; fg = "yellow"; }
        { name = ".luacheckrc"; text = ""; fg = "blue"; }
        { name = ".luaurc"; text = ""; fg = "blue"; }
        { name = ".mailmap"; text = "󰊢"; fg = "red"; }
        { name = ".nanorc"; text = ""; fg = "green"; }
        { name = ".npmignore"; text = ""; fg = "red"; }
        { name = ".npmrc"; text = ""; fg = "red"; }
        { name = ".nuxtrc"; text = "󱄆"; fg = "green"; }
        { name = ".nvmrc"; text = ""; fg = "green"; }
        { name = ".pnpmfile.cjs"; text = ""; fg = "lightyellow"; }
        { name = ".pre-commit-config.yaml"; text = "󰛢"; fg = "gray"; }
        { name = ".prettierignore"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.cjs"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.js"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.json"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.json5"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.mjs"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.toml"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.yaml"; text = ""; fg = "lightmagenta"; }
        { name = ".prettierrc.yml"; text = ""; fg = "lightmagenta"; }
        { name = ".pylintrc"; text = ""; fg = "yellow"; }
        { name = ".settings.json"; text = ""; fg = "yellow"; }
        { name = ".SRCINFO"; text = "󰣇"; fg = "cyan"; }
        { name = ".vimrc"; text = ""; fg = "green"; }
        { name = ".Xauthority"; text = ""; fg = "gray"; }
        { name = ".xinitrc"; text = ""; fg = "gray"; }
        { name = ".Xresources"; text = ""; fg = "gray"; }
        { name = ".xsession"; text = ""; fg = "gray"; }
        { name = ".zprofile"; text = ""; fg = "green"; }
        { name = ".zshenv"; text = ""; fg = "green"; }
        { name = ".zshrc"; text = ""; fg = "green"; }
        { name = "_gvimrc"; text = ""; fg = "green"; }
        { name = "_vimrc"; text = ""; fg = "green"; }
        { name = "AUTHORS"; text = ""; fg = "cyan"; }
        { name = "AUTHORS.txt"; text = ""; fg = "cyan"; }
        { name = "brewfile"; text = ""; fg = "lightyellow"; }
        { name = "bspwmrc"; text = ""; fg = "gray"; }
        { name = "build"; text = ""; fg = "cyan"; }
        { name = "build.gradle"; text = ""; fg = "green"; }
        { name = "build.zig.zon"; text = ""; fg = "red"; }
        { name = "bun.lock"; text = ""; fg = "lightmagenta"; }
        { name = "bun.lockb"; text = ""; fg = "lightmagenta"; }
        { name = "cantorrc"; text = ""; fg = "cyan"; }
        { name = "checkhealth"; text = "󰓙"; fg = "green"; }
        { name = "cmakelists.txt"; text = ""; fg = "cyan"; }
        { name = "code_of_conduct"; text = ""; fg = "red"; }
        { name = "code_of_conduct.md"; text = ""; fg = "red"; }
        { name = "commit_editmsg"; text = ""; fg = "red"; }
        { name = "commitlint.config.js"; text = "󰜘"; fg = "red"; }
        { name = "commitlint.config.ts"; text = "󰜘"; fg = "red"; }
        { name = "compose.yaml"; text = "󰡨"; fg = "blue"; }
        { name = "compose.yml"; text = "󰡨"; fg = "blue"; }
        { name = "config"; text = ""; fg = "yellow"; }
        { name = "containerfile"; text = "󰡨"; fg = "blue"; }
        { name = "copying"; text = ""; fg = "yellow"; }
        { name = "copying.lesser"; text = ""; fg = "yellow"; }
        { name = "Directory.Build.props"; text = ""; fg = "magenta"; }
        { name = "Directory.Build.targets"; text = ""; fg = "magenta"; }
        { name = "Directory.Packages.props"; text = ""; fg = "magenta"; }
        { name = "docker-compose.yaml"; text = "󰡨"; fg = "blue"; }
        { name = "docker-compose.yml"; text = "󰡨"; fg = "blue"; }
        { name = "dockerfile"; text = "󰡨"; fg = "blue"; }
        { name = "eslint.config.cjs"; text = ""; fg = "magenta"; }
        { name = "eslint.config.js"; text = ""; fg = "magenta"; }
        { name = "eslint.config.mjs"; text = ""; fg = "magenta"; }
        { name = "eslint.config.ts"; text = ""; fg = "magenta"; }
        { name = "ext_typoscript_setup.txt"; text = ""; fg = "lightblue"; }
        { name = "favicon.ico"; text = ""; fg = "lightyellow"; }
        { name = "fp-info-cache"; text = ""; fg = "cyan"; }
        { name = "fp-lib-table"; text = ""; fg = "cyan"; }
        { name = "FreeCAD.conf"; text = ""; fg = "yellow"; }
        { name = "Gemfile"; text = ""; fg = "red"; }
        { name = "gnumakefile"; text = ""; fg = "yellow"; }
        { name = "go.mod"; text = ""; fg = "cyan"; }
        { name = "go.sum"; text = ""; fg = "cyan"; }
        { name = "go.work"; text = ""; fg = "cyan"; }
        { name = "gradle-wrapper.properties"; text = ""; fg = "green"; }
        { name = "gradle.properties"; text = ""; fg = "green"; }
        { name = "gradlew"; text = ""; fg = "green"; }
        { name = "groovy"; text = ""; fg = "cyan"; }
        { name = "gruntfile.babel.js"; text = ""; fg = "lightyellow"; }
        { name = "gruntfile.coffee"; text = ""; fg = "lightyellow"; }
        { name = "gruntfile.js"; text = ""; fg = "lightyellow"; }
        { name = "gruntfile.ts"; text = ""; fg = "lightyellow"; }
        { name = "gtkrc"; text = ""; fg = "green"; }
        { name = "gulpfile.babel.js"; text = ""; fg = "lightred"; }
        { name = "gulpfile.coffee"; text = ""; fg = "lightred"; }
        { name = "gulpfile.js"; text = ""; fg = "lightred"; }
        { name = "gulpfile.ts"; text = ""; fg = "lightred"; }
        { name = "hypridle.conf"; text = ""; fg = "cyan"; }
        { name = "hyprland.conf"; text = ""; fg = "cyan"; }
        { name = "hyprlandd.conf"; text = ""; fg = "cyan"; }
        { name = "hyprlock.conf"; text = ""; fg = "cyan"; }
        { name = "hyprpaper.conf"; text = ""; fg = "cyan"; }
        { name = "hyprsunset.conf"; text = ""; fg = "cyan"; }
        { name = "i18n.config.js"; text = "󰗊"; fg = "yellow"; }
        { name = "i18n.config.ts"; text = "󰗊"; fg = "yellow"; }
        { name = "i3blocks.conf"; text = ""; fg = "cyan"; }
        { name = "i3status.conf"; text = ""; fg = "cyan"; }
        { name = "index.theme"; text = ""; fg = "yellow"; }
        { name = "ionic.config.json"; text = ""; fg = "blue"; }
        { name = "Jenkinsfile"; text = ""; fg = "red"; }
        { name = "justfile"; text = ""; fg = "yellow"; }
        { name = "kalgebrarc"; text = ""; fg = "cyan"; }
        { name = "kdeglobals"; text = ""; fg = "cyan"; }
        { name = "kdenlive-layoutsrc"; text = ""; fg = "magenta"; }
        { name = "kdenliverc"; text = ""; fg = "magenta"; }
        { name = "kritadisplayrc"; text = ""; fg = "lightmagenta"; }
        { name = "kritarc"; text = ""; fg = "lightmagenta"; }
        { name = "license"; text = ""; fg = "yellow"; }
        { name = "license.md"; text = ""; fg = "yellow"; }
        { name = "lxde-rc.xml"; text = ""; fg = "cyan"; }
        { name = "lxqt.conf"; text = ""; fg = "cyan"; }
        { name = "makefile"; text = ""; fg = "yellow"; }
        { name = "mix.lock"; text = ""; fg = "lightblue"; }
        { name = "mpv.conf"; text = ""; fg = "magenta"; }
        { name = "next.config.cjs"; text = ""; fg = "white"; }
        { name = "next.config.js"; text = ""; fg = "white"; }
        { name = "next.config.ts"; text = ""; fg = "white"; }
        { name = "node_modules"; text = ""; fg = "green"; }
        { name = "nuxt.config.cjs"; text = "󱄆"; fg = "green"; }
        { name = "nuxt.config.js"; text = "󱄆"; fg = "green"; }
        { name = "nuxt.config.mjs"; text = "󱄆"; fg = "green"; }
        { name = "nuxt.config.ts"; text = "󱄆"; fg = "green"; }
        { name = "package-lock.json"; text = ""; fg = "yellow"; }
        { name = "package.json"; text = ""; fg = "yellow"; }
        { name = "PKGBUILD"; text = ""; fg = "cyan"; }
        { name = "platformio.ini"; text = ""; fg = "lightred"; }
        { name = "playwright.config.cjs"; text = ""; fg = "green"; }
        { name = "playwright.config.cts"; text = ""; fg = "green"; }
        { name = "playwright.config.js"; text = ""; fg = "green"; }
        { name = "playwright.config.mjs"; text = ""; fg = "green"; }
        { name = "playwright.config.mts"; text = ""; fg = "green"; }
        { name = "playwright.config.ts"; text = ""; fg = "green"; }
        { name = "pnpm-lock.yaml"; text = ""; fg = "lightyellow"; }
        { name = "pnpm-workspace.yaml"; text = ""; fg = "lightyellow"; }
        { name = "pom.xml"; text = ""; fg = "red"; }
        { name = "prettier.config.cjs"; text = ""; fg = "lightmagenta"; }
        { name = "prettier.config.js"; text = ""; fg = "lightmagenta"; }
        { name = "prettier.config.mjs"; text = ""; fg = "lightmagenta"; }
        { name = "prettier.config.ts"; text = ""; fg = "lightmagenta"; }
        { name = "prisma.config.mts"; text = ""; fg = "cyan"; }
        { name = "prisma.config.ts"; text = ""; fg = "cyan"; }
        { name = "procfile"; text = ""; fg = "magenta"; }
        { name = "PrusaSlicer.ini"; text = ""; fg = "magenta"; }
        { name = "PrusaSlicerGcodeViewer.ini"; text = ""; fg = "magenta"; }
        { name = "py.typed"; text = ""; fg = "yellow"; }
        { name = "QtProject.conf"; text = ""; fg = "green"; }
        { name = "rakefile"; text = ""; fg = "red"; }
        { name = "readme"; text = "󰂺"; fg = "blue"; }
        { name = "readme.md"; text = "󰂺"; fg = "blue"; }
        { name = "rmd"; text = ""; fg = "blue"; }
        { name = "robots.txt"; text = "󰚩"; fg = "lightred"; }
        { name = "security"; text = "󰒃"; fg = "red"; }
        { name = "security.md"; text = "󰒃"; fg = "red"; }
        { name = "settings.gradle"; text = ""; fg = "green"; }
        { name = "svelte.config.js"; text = ""; fg = "red"; }
        { name = "sxhkdrc"; text = ""; fg = "gray"; }
        { name = "sym-lib-table"; text = ""; fg = "cyan"; }
        { name = "tailwind.config.js"; text = "󱏿"; fg = "lightcyan"; }
        { name = "tailwind.config.mjs"; text = "󱏿"; fg = "lightcyan"; }
        { name = "tailwind.config.ts"; text = "󱏿"; fg = "lightcyan"; }
        { name = "tmux.conf"; text = ""; fg = "green"; }
        { name = "tmux.conf.local"; text = ""; fg = "green"; }
        { name = "tsconfig.json"; text = ""; fg = "blue"; }
        { name = "unlicense"; text = ""; fg = "yellow"; }
        { name = "vagrantfile"; text = ""; fg = "cyan"; }
        { name = "vercel.json"; text = ""; fg = "darkgray"; }
        { name = "vite.config.cjs"; text = ""; fg = "yellow"; }
        { name = "vite.config.cts"; text = ""; fg = "yellow"; }
        { name = "vite.config.js"; text = ""; fg = "yellow"; }
        { name = "vite.config.mjs"; text = ""; fg = "yellow"; }
        { name = "vite.config.mts"; text = ""; fg = "yellow"; }
        { name = "vite.config.ts"; text = ""; fg = "yellow"; }
        { name = "vitest.config.cjs"; text = ""; fg = "yellow"; }
        { name = "vitest.config.cts"; text = ""; fg = "yellow"; }
        { name = "vitest.config.js"; text = ""; fg = "yellow"; }
        { name = "vitest.config.mjs"; text = ""; fg = "yellow"; }
        { name = "vitest.config.mts"; text = ""; fg = "yellow"; }
        { name = "vitest.config.ts"; text = ""; fg = "yellow"; }
        { name = "vlcrc"; text = "󰕼"; fg = "red"; }
        { name = "webpack"; text = "󰜫"; fg = "lightblue"; }
        { name = "weston.ini"; text = ""; fg = "cyan"; }
        { name = "workspace"; text = ""; fg = "cyan"; }
        { name = "wrangler.jsonc"; text = ""; fg = "lightred"; }
        { name = "wrangler.toml"; text = ""; fg = "lightred"; }
        { name = "xdph.conf"; text = ""; fg = "cyan"; }
        { name = "xmobarrc"; text = ""; fg = "gray"; }
        { name = "xmobarrc.hs"; text = ""; fg = "gray"; }
        { name = "xmonad.hs"; text = ""; fg = "gray"; }
        { name = "xorg.conf"; text = ""; fg = "gray"; }
        { name = "xsettingsd.conf"; text = ""; fg = "gray"; }
    ];

    exts = [
        { name = "3gp"; text = ""; fg = "magenta"; }
        { name = "3mf"; text = "󰆧"; fg = "lightred"; }
        { name = "7z"; text = ""; fg = "red"; }
        { name = "a"; text = ""; fg = "gray"; }
        { name = "aac"; text = ""; fg = "yellow"; }
        { name = "ada"; text = ""; fg = "lightblue"; }
        { name = "adb"; text = ""; fg = "lightblue"; }
        { name = "ads"; text = ""; fg = "lightblue"; }
        { name = "ai"; text = ""; fg = "magenta"; }
        { name = "aif"; text = ""; fg = "yellow"; }
        { name = "aiff"; text = ""; fg = "yellow"; }
        { name = "android"; text = ""; fg = "green"; }
        { name = "ape"; text = ""; fg = "yellow"; }
        { name = "apk"; text = ""; fg = "green"; }
        { name = "apl"; text = ""; fg = "lightblue"; }
        { name = "app"; text = ""; fg = "cyan"; }
        { name = "applescript"; text = ""; fg = "cyan"; }
        { name = "asc"; text = "󰦝"; fg = "lightgreen"; }
        { name = "asm"; text = ""; fg = "magenta"; }
        { name = "ass"; text = "󰨖"; fg = "magenta"; }
        { name = "astro"; text = ""; fg = "magenta"; }
        { name = "avif"; text = ""; fg = "magenta"; }
        { name = "awk"; text = ""; fg = "green"; }
        { name = "azcli"; text = ""; fg = "lightblue"; }
        { name = "bak"; text = "󰁯"; fg = "gray"; }
        { name = "bash"; text = ""; fg = "green"; }
        { name = "bat"; text = ""; fg = "gray"; }
        { name = "bazel"; text = ""; fg = "green"; }
        { name = "bib"; text = "󱉟"; fg = "lightyellow"; }
        { name = "bicep"; text = ""; fg = "cyan"; }
        { name = "bicepparam"; text = ""; fg = "cyan"; }
        { name = "bin"; text = ""; fg = "darkgray"; }
        { name = "blade.php"; text = ""; fg = "lightred"; }
        { name = "blend"; text = "󰂫"; fg = "lightred"; }
        { name = "blp"; text = "󰺾"; fg = "green"; }
        { name = "bmp"; text = ""; fg = "magenta"; }
        { name = "bqn"; text = ""; fg = "lightblue"; }
        { name = "brep"; text = "󰻫"; fg = "lightred"; }
        { name = "bz"; text = ""; fg = "red"; }
        { name = "bz2"; text = ""; fg = "red"; }
        { name = "bz3"; text = ""; fg = "red"; }
        { name = "bzl"; text = ""; fg = "green"; }
        { name = "c"; text = ""; fg = "blue"; }
        { name = "c++"; text = ""; fg = "lightmagenta"; }
        { name = "cache"; text = ""; fg = "gray"; }
        { name = "cast"; text = ""; fg = "magenta"; }
        { name = "cbl"; text = ""; fg = "lightblue"; }
        { name = "cc"; text = ""; fg = "lightmagenta"; }
        { name = "ccm"; text = ""; fg = "lightmagenta"; }
        { name = "cfc"; text = ""; fg = "lightred"; }
        { name = "cfg"; text = ""; fg = "yellow"; }
        { name = "cfm"; text = ""; fg = "lightred"; }
        { name = "cjs"; text = ""; fg = "yellow"; }
        { name = "clj"; text = ""; fg = "green"; }
        { name = "cljc"; text = ""; fg = "green"; }
        { name = "cljd"; text = ""; fg = "green"; }
        { name = "cljs"; text = ""; fg = "green"; }
        { name = "cmake"; text = ""; fg = "cyan"; }
        { name = "cob"; text = ""; fg = "lightblue"; }
        { name = "cobol"; text = ""; fg = "lightblue"; }
        { name = "coffee"; text = ""; fg = "lightmagenta"; }
        { name = "conda"; text = ""; fg = "green"; }
        { name = "conf"; text = ""; fg = "yellow"; }
        { name = "config.ru"; text = ""; fg = "red"; }
        { name = "cow"; text = "󰆚"; fg = "gray"; }
        { name = "cp"; text = ""; fg = "lightmagenta"; }
        { name = "cpp"; text = ""; fg = "lightmagenta"; }
        { name = "cppm"; text = ""; fg = "lightmagenta"; }
        { name = "cpy"; text = ""; fg = "lightblue"; }
        { name = "cr"; text = ""; fg = "cyan"; }
        { name = "crdownload"; text = ""; fg = "gray"; }
        { name = "cs"; text = "󰌛"; fg = "magenta"; }
        { name = "csh"; text = ""; fg = "green"; }
        { name = "cshtml"; text = "󱦗"; fg = "magenta"; }
        { name = "cson"; text = ""; fg = "yellow"; }
        { name = "csproj"; text = "󰪮"; fg = "magenta"; }
        { name = "css"; text = ""; fg = "lightblue"; }
        { name = "csv"; text = ""; fg = "green"; }
        { name = "cts"; text = ""; fg = "blue"; }
        { name = "cu"; text = ""; fg = "green"; }
        { name = "cue"; text = "󰲹"; fg = "yellow"; }
        { name = "cuh"; text = ""; fg = "green"; }
        { name = "cxx"; text = ""; fg = "lightmagenta"; }
        { name = "cxxm"; text = ""; fg = "lightmagenta"; }
        { name = "d"; text = ""; fg = "red"; }
        { name = "d.ts"; text = ""; fg = "blue"; }
        { name = "dart"; text = ""; fg = "lightblue"; }
        { name = "db"; text = ""; fg = "lightblue"; }
        { name = "dconf"; text = ""; fg = "cyan"; }
        { name = "desktop"; text = ""; fg = "yellow"; }
        { name = "diff"; text = ""; fg = "red"; }
        { name = "dll"; text = ""; fg = "gray"; }
        { name = "doc"; text = "󰈬"; fg = "blue"; }
        { name = "Dockerfile"; text = "󰡨"; fg = "blue"; }
        { name = "dockerignore"; text = "󰡨"; fg = "blue"; }
        { name = "docx"; text = "󰈬"; fg = "blue"; }
        { name = "dot"; text = "󱁉"; fg = "gray"; }
        { name = "download"; text = ""; fg = "gray"; }
        { name = "drl"; text = ""; fg = "lightgreen"; }
        { name = "dropbox"; text = ""; fg = "blue"; }
        { name = "dump"; text = ""; fg = "lightblue"; }
        { name = "dwg"; text = "󰻫"; fg = "lightred"; }
        { name = "dxf"; text = "󰻫"; fg = "lightred"; }
        { name = "ebook"; text = ""; fg = "blue"; }
        { name = "ebuild"; text = ""; fg = "cyan"; }
        { name = "edn"; text = ""; fg = "green"; }
        { name = "eex"; text = ""; fg = "magenta"; }
        { name = "ejs"; text = ""; fg = "yellow"; }
        { name = "el"; text = ""; fg = "magenta"; }
        { name = "elc"; text = ""; fg = "magenta"; }
        { name = "elf"; text = ""; fg = "darkgray"; }
        { name = "elm"; text = ""; fg = "cyan"; }
        { name = "eln"; text = ""; fg = "magenta"; }
        { name = "env"; text = ""; fg = "yellow"; }
        { name = "eot"; text = ""; fg = "cyan"; }
        { name = "epp"; text = ""; fg = "magenta"; }
        { name = "epub"; text = ""; fg = "blue"; }
        { name = "erb"; text = ""; fg = "red"; }
        { name = "erl"; text = ""; fg = "red"; }
        { name = "ex"; text = ""; fg = "magenta"; }
        { name = "exe"; text = ""; fg = "darkgray"; }
        { name = "exs"; text = ""; fg = "magenta"; }
        { name = "f#"; text = ""; fg = "cyan"; }
        { name = "f3d"; text = "󰻫"; fg = "lightred"; }
        { name = "f90"; text = "󱈚"; fg = "lightblue"; }
        { name = "fbx"; text = "󰆧"; fg = "lightred"; }
        { name = "fcbak"; text = ""; fg = "yellow"; }
        { name = "fcmacro"; text = ""; fg = "yellow"; }
        { name = "fcmat"; text = ""; fg = "yellow"; }
        { name = "fcparam"; text = ""; fg = "yellow"; }
        { name = "fcscript"; text = ""; fg = "yellow"; }
        { name = "fcstd"; text = ""; fg = "yellow"; }
        { name = "fcstd1"; text = ""; fg = "yellow"; }
        { name = "fctb"; text = ""; fg = "yellow"; }
        { name = "fctl"; text = ""; fg = "yellow"; }
        { name = "fdmdownload"; text = ""; fg = "gray"; }
        { name = "feature"; text = ""; fg = "blue"; }
        { name = "fish"; text = ""; fg = "green"; }
        { name = "flac"; text = ""; fg = "yellow"; }
        { name = "flc"; text = ""; fg = "cyan"; }
        { name = "flf"; text = ""; fg = "cyan"; }
        { name = "fnl"; text = ""; fg = "magenta"; }
        { name = "fodg"; text = ""; fg = "green"; }
        { name = "fodp"; text = ""; fg = "green"; }
        { name = "fods"; text = ""; fg = "green"; }
        { name = "fodt"; text = ""; fg = "blue"; }
        { name = "frag"; text = ""; fg = "lightblue"; }
        { name = "fs"; text = ""; fg = "cyan"; }
        { name = "fsi"; text = ""; fg = "cyan"; }
        { name = "fsscript"; text = ""; fg = "cyan"; }
        { name = "fsx"; text = ""; fg = "cyan"; }
        { name = "gcode"; text = "󰐫"; fg = "lightred"; }
        { name = "gd"; text = ""; fg = "cyan"; }
        { name = "gemspec"; text = ""; fg = "red"; }
        { name = "geom"; text = ""; fg = "lightblue"; }
        { name = "gif"; text = ""; fg = "magenta"; }
        { name = "git"; text = ""; fg = "red"; }
        { name = "glb"; text = ""; fg = "lightblue"; }
        { name = "gleam"; text = ""; fg = "lightmagenta"; }
        { name = "glsl"; text = ""; fg = "lightblue"; }
        { name = "gnumakefile"; text = ""; fg = "yellow"; }
        { name = "go"; text = ""; fg = "cyan"; }
        { name = "godot"; text = ""; fg = "blue"; }
        { name = "gpr"; text = ""; fg = "lightblue"; }
        { name = "gql"; text = ""; fg = "magenta"; }
        { name = "gradle"; text = ""; fg = "green"; }
        { name = "graphql"; text = ""; fg = "magenta"; }
        { name = "gresource"; text = ""; fg = "green"; }
        { name = "gv"; text = "󱁉"; fg = "gray"; }
        { name = "gz"; text = ""; fg = "red"; }
        { name = "h"; text = ""; fg = "blue"; }
        { name = "haml"; text = ""; fg = "red"; }
        { name = "hbs"; text = ""; fg = "lightred"; }
        { name = "heex"; text = ""; fg = "magenta"; }
        { name = "hex"; text = ""; fg = "lightblue"; }
        { name = "hh"; text = ""; fg = "lightmagenta"; }
        { name = "hpp"; text = ""; fg = "lightmagenta"; }
        { name = "hrl"; text = ""; fg = "lightblue"; }
        { name = "hs"; text = ""; fg = "magenta"; }
        { name = "htm"; text = ""; fg = "red"; }
        { name = "html"; text = ""; fg = "red"; }
        { name = "http"; text = ""; fg = "magenta"; }
        { name = "huff"; text = "󰡘"; fg = "lightred"; }
        { name = "hurl"; text = ""; fg = "lightred"; }
        { name = "hx"; text = ""; fg = "cyan"; }
        { name = "hxx"; text = ""; fg = "lightmagenta"; }
        { name = "ical"; text = ""; fg = "lightblue"; }
        { name = "icalendar"; text = ""; fg = "lightblue"; }
        { name = "ico"; text = ""; fg = "magenta"; }
        { name = "ics"; text = ""; fg = "lightblue"; }
        { name = "ifb"; text = ""; fg = "lightblue"; }
        { name = "ifc"; text = "󰻫"; fg = "lightred"; }
        { name = "ige"; text = "󰻫"; fg = "lightred"; }
        { name = "iges"; text = "󰻫"; fg = "lightred"; }
        { name = "igs"; text = "󰻫"; fg = "lightred"; }
        { name = "image"; text = ""; fg = "magenta"; }
        { name = "img"; text = ""; fg = "magenta"; }
        { name = "import"; text = ""; fg = "gray"; }
        { name = "info"; text = ""; fg = "lightblue"; }
        { name = "ini"; text = ""; fg = "yellow"; }
        { name = "ino"; text = ""; fg = "cyan"; }
        { name = "ipynb"; text = ""; fg = "red"; }
        { name = "iso"; text = ""; fg = "magenta"; }
        { name = "ixx"; text = ""; fg = "lightmagenta"; }
        { name = "jar"; text = ""; fg = "red"; }
        { name = "java"; text = ""; fg = "red"; }
        { name = "jl"; text = ""; fg = "magenta"; }
        { name = "jpeg"; text = ""; fg = "magenta"; }
        { name = "jpg"; text = ""; fg = "magenta"; }
        { name = "js"; text = ""; fg = "yellow"; }
        { name = "json"; text = ""; fg = "yellow"; }
        { name = "json5"; text = ""; fg = "yellow"; }
        { name = "jsonc"; text = ""; fg = "yellow"; }
        { name = "jsx"; text = ""; fg = "cyan"; }
        { name = "jwmrc"; text = ""; fg = "yellow"; }
        { name = "jxl"; text = ""; fg = "magenta"; }
        { name = "kbx"; text = "󰯄"; fg = "lightblue"; }
        { name = "kdb"; text = ""; fg = "lightblue"; }
        { name = "kdbx"; text = ""; fg = "lightblue"; }
        { name = "kdenlive"; text = ""; fg = "magenta"; }
        { name = "kdenlivetitle"; text = ""; fg = "magenta"; }
        { name = "kicad_dru"; text = ""; fg = "blue"; }
        { name = "kicad_mod"; text = ""; fg = "blue"; }
        { name = "kicad_pcb"; text = ""; fg = "blue"; }
        { name = "kicad_prl"; text = ""; fg = "blue"; }
        { name = "kicad_pro"; text = ""; fg = "blue"; }
        { name = "kicad_sch"; text = ""; fg = "blue"; }
        { name = "kicad_sym"; text = ""; fg = "blue"; }
        { name = "kicad_wks"; text = ""; fg = "blue"; }
        { name = "ko"; text = ""; fg = "darkgray"; }
        { name = "kpp"; text = ""; fg = "lightmagenta"; }
        { name = "kra"; text = ""; fg = "lightmagenta"; }
        { name = "krz"; text = ""; fg = "lightmagenta"; }
        { name = "ksh"; text = ""; fg = "green"; }
        { name = "kt"; text = ""; fg = "magenta"; }
        { name = "kts"; text = ""; fg = "magenta"; }
        { name = "lck"; text = ""; fg = "lightyellow"; }
        { name = "leex"; text = ""; fg = "magenta"; }
        { name = "less"; text = ""; fg = "lightblue"; }
        { name = "lff"; text = ""; fg = "cyan"; }
        { name = "lhs"; text = ""; fg = "magenta"; }
        { name = "lib"; text = ""; fg = "gray"; }
        { name = "license"; text = ""; fg = "yellow"; }
        { name = "liquid"; text = ""; fg = "lightblue"; }
        { name = "lock"; text = ""; fg = "lightyellow"; }
        { name = "log"; text = "󰌱"; fg = "gray"; }
        { name = "lrc"; text = "󰨖"; fg = "magenta"; }
        { name = "lua"; text = ""; fg = "blue"; }
        { name = "luac"; text = ""; fg = "blue"; }
        { name = "luau"; text = ""; fg = "blue"; }
        { name = "m"; text = ""; fg = "magenta"; }
        { name = "m3u"; text = "󰲹"; fg = "yellow"; }
        { name = "m3u8"; text = "󰲹"; fg = "yellow"; }
        { name = "m4a"; text = ""; fg = "yellow"; }
        { name = "m4v"; text = ""; fg = "magenta"; }
        { name = "magnet"; text = ""; fg = "red"; }
        { name = "makefile"; text = ""; fg = "yellow"; }
        { name = "markdown"; text = ""; fg = "blue"; }
        { name = "material"; text = ""; fg = "cyan"; }
        { name = "md"; text = ""; fg = "blue"; }
        { name = "md5"; text = "󰕥"; fg = "gray"; }
        { name = "mdx"; text = ""; fg = "blue"; }
        { name = "mint"; text = "󰌪"; fg = "green"; }
        { name = "mjs"; text = ""; fg = "yellow"; }
        { name = "mk"; text = ""; fg = "yellow"; }
        { name = "mkv"; text = ""; fg = "magenta"; }
        { name = "ml"; text = ""; fg = "red"; }
        { name = "mli"; text = ""; fg = "red"; }
        { name = "mm"; text = ""; fg = "lightmagenta"; }
        { name = "mo"; text = ""; fg = "lightyellow"; }
        { name = "mobi"; text = ""; fg = "blue"; }
        { name = "mojo"; text = ""; fg = "red"; }
        { name = "mov"; text = ""; fg = "magenta"; }
        { name = "mp3"; text = ""; fg = "yellow"; }
        { name = "mp4"; text = ""; fg = "magenta"; }
        { name = "mpp"; text = ""; fg = "lightmagenta"; }
        { name = "msf"; text = ""; fg = "gray"; }
        { name = "mts"; text = ""; fg = "blue"; }
        { name = "mustache"; text = ""; fg = "lightred"; }
        { name = "nfo"; text = ""; fg = "lightblue"; }
        { name = "nim"; text = ""; fg = "yellow"; }
        { name = "nix"; text = ""; fg = "lightblue"; }
        { name = "norg"; text = ""; fg = "cyan"; }
        { name = "nswag"; text = ""; fg = "yellow"; }
        { name = "nu"; text = ""; fg = "green"; }
        { name = "o"; text = ""; fg = "darkgray"; }
        { name = "obj"; text = "󰆧"; fg = "lightred"; }
        { name = "odf"; text = ""; fg = "blue"; }
        { name = "odg"; text = ""; fg = "green"; }
        { name = "odin"; text = "󰟢"; fg = "lightblue"; }
        { name = "odp"; text = ""; fg = "green"; }
        { name = "ods"; text = ""; fg = "green"; }
        { name = "odt"; text = ""; fg = "blue"; }
        { name = "oga"; text = ""; fg = "yellow"; }
        { name = "ogg"; text = ""; fg = "yellow"; }
        { name = "ogv"; text = ""; fg = "magenta"; }
        { name = "ogx"; text = ""; fg = "magenta"; }
        { name = "opus"; text = ""; fg = "yellow"; }
        { name = "org"; text = ""; fg = "green"; }
        { name = "otf"; text = ""; fg = "cyan"; }
        { name = "out"; text = ""; fg = "darkgray"; }
        { name = "part"; text = ""; fg = "gray"; }
        { name = "patch"; text = ""; fg = "green"; }
        { name = "pck"; text = ""; fg = "gray"; }
        { name = "pcm"; text = ""; fg = "yellow"; }
        { name = "pdf"; text = ""; fg = "red"; }
        { name = "php"; text = ""; fg = "magenta"; }
        { name = "pl"; text = ""; fg = "blue"; }
        { name = "pls"; text = "󰲹"; fg = "yellow"; }
        { name = "ply"; text = "󰆧"; fg = "lightred"; }
        { name = "pm"; text = ""; fg = "blue"; }
        { name = "png"; text = ""; fg = "magenta"; }
        { name = "po"; text = ""; fg = "lightblue"; }
        { name = "pot"; text = ""; fg = "lightblue"; }
        { name = "pp"; text = ""; fg = "magenta"; }
        { name = "ppt"; text = "󰈧"; fg = "red"; }
        { name = "pptx"; text = "󰈧"; fg = "red"; }
        { name = "prisma"; text = ""; fg = "cyan"; }
        { name = "pro"; text = ""; fg = "lightblue"; }
        { name = "ps1"; text = "󰨊"; fg = "cyan"; }
        { name = "psb"; text = ""; fg = "lightblue"; }
        { name = "psd"; text = ""; fg = "lightblue"; }
        { name = "psd1"; text = "󰨊"; fg = "cyan"; }
        { name = "psm1"; text = "󰨊"; fg = "cyan"; }
        { name = "pub"; text = "󰷖"; fg = "lightblue"; }
        { name = "pxd"; text = ""; fg = "yellow"; }
        { name = "pxi"; text = ""; fg = "yellow"; }
        { name = "py"; text = ""; fg = "yellow"; }
        { name = "pyc"; text = ""; fg = "yellow"; }
        { name = "pyd"; text = ""; fg = "yellow"; }
        { name = "pyi"; text = ""; fg = "yellow"; }
        { name = "pyo"; text = ""; fg = "yellow"; }
        { name = "pyw"; text = ""; fg = "yellow"; }
        { name = "pyx"; text = ""; fg = "yellow"; }
        { name = "qm"; text = ""; fg = "lightblue"; }
        { name = "qml"; text = ""; fg = "green"; }
        { name = "qrc"; text = ""; fg = "green"; }
        { name = "qss"; text = ""; fg = "green"; }
        { name = "query"; text = ""; fg = "magenta"; }
        { name = "R"; text = "󰟔"; fg = "lightblue"; }
        { name = "r"; text = "󰟔"; fg = "lightblue"; }
        { name = "rake"; text = ""; fg = "yellow"; }
        { name = "rar"; text = ""; fg = "red"; }
        { name = "rasi"; text = ""; fg = "green"; }
        { name = "razor"; text = "󱦘"; fg = "magenta"; }
        { name = "rb"; text = ""; fg = "red"; }
        { name = "res"; text = ""; fg = "magenta"; }
        { name = "resi"; text = ""; fg = "magenta"; }
        { name = "rlib"; text = ""; fg = "red"; }
        { name = "rmd"; text = ""; fg = "blue"; }
        { name = "rproj"; text = "󰗆"; fg = "green"; }
        { name = "rs"; text = ""; fg = "red"; }
        { name = "rss"; text = ""; fg = "red"; }
        { name = "s"; text = ""; fg = "darkgray"; }
        { name = "sass"; text = ""; fg = "lightred"; }
        { name = "sbt"; text = ""; fg = "red"; }
        { name = "sc"; text = ""; fg = "red"; }
        { name = "scad"; text = ""; fg = "red"; }
        { name = "scala"; text = ""; fg = "red"; }
        { name = "scm"; text = "󰘧"; fg = "green"; }
        { name = "scss"; text = ""; fg = "lightred"; }
        { name = "sh"; text = ""; fg = "green"; }
        { name = "sha1"; text = "󰕥"; fg = "gray"; }
        { name = "sha224"; text = "󰕥"; fg = "gray"; }
        { name = "sha256"; text = "󰕥"; fg = "gray"; }
        { name = "sha384"; text = "󰕥"; fg = "gray"; }
        { name = "sha512"; text = "󰕥"; fg = "gray"; }
        { name = "sig"; text = "󰘧"; fg = "magenta"; }
        { name = "signature"; text = "󰘧"; fg = "magenta"; }
        { name = "skp"; text = "󰻫"; fg = "lightred"; }
        { name = "sldasm"; text = "󰻫"; fg = "lightred"; }
        { name = "sldprt"; text = "󰻫"; fg = "lightred"; }
        { name = "slim"; text = ""; fg = "red"; }
        { name = "sln"; text = ""; fg = "magenta"; }
        { name = "slnx"; text = ""; fg = "magenta"; }
        { name = "slvs"; text = "󰻫"; fg = "lightred"; }
        { name = "sml"; text = "󰘧"; fg = "green"; }
        { name = "so"; text = ""; fg = "darkgray"; }
        { name = "sol"; text = ""; fg = "gray"; }
        { name = "spec.js"; text = ""; fg = "yellow"; }
        { name = "spec.jsx"; text = ""; fg = "yellow"; }
        { name = "spec.ts"; text = ""; fg = "yellow"; }
        { name = "spec.tsx"; text = ""; fg = "yellow"; }
        { name = "spx"; text = ""; fg = "yellow"; }
        { name = "sql"; text = ""; fg = "lightblue"; }
        { name = "sqlite"; text = ""; fg = "lightblue"; }
        { name = "sqlite3"; text = ""; fg = "lightblue"; }
        { name = "srt"; text = "󰨖"; fg = "magenta"; }
        { name = "ssa"; text = "󰨖"; fg = "magenta"; }
        { name = "ste"; text = "󰻫"; fg = "lightred"; }
        { name = "step"; text = "󰻫"; fg = "lightred"; }
        { name = "stl"; text = "󰆧"; fg = "lightred"; }
        { name = "stories.js"; text = ""; fg = "magenta"; }
        { name = "stories.jsx"; text = ""; fg = "magenta"; }
        { name = "stories.mjs"; text = ""; fg = "magenta"; }
        { name = "stories.svelte"; text = ""; fg = "magenta"; }
        { name = "stories.ts"; text = ""; fg = "magenta"; }
        { name = "stories.tsx"; text = ""; fg = "magenta"; }
        { name = "stories.vue"; text = ""; fg = "magenta"; }
        { name = "stp"; text = "󰻫"; fg = "lightred"; }
        { name = "strings"; text = ""; fg = "lightblue"; }
        { name = "styl"; text = ""; fg = "green"; }
        { name = "sub"; text = "󰨖"; fg = "magenta"; }
        { name = "sublime"; text = ""; fg = "red"; }
        { name = "suo"; text = ""; fg = "darkgray"; }
        { name = "sv"; text = "󰍛"; fg = "lightblue"; }
        { name = "svelte"; text = ""; fg = "red"; }
        { name = "svg"; text = "󰜡"; fg = "lightred"; }
        { name = "svgz"; text = "󰜡"; fg = "lightred"; }
        { name = "svh"; text = "󰍛"; fg = "lightblue"; }
        { name = "swift"; text = ""; fg = "red"; }
        { name = "t"; text = ""; fg = "red"; }
        { name = "tbc"; text = "󰛓"; fg = "cyan"; }
        { name = "tcl"; text = "󰛓"; fg = "cyan"; }
        { name = "templ"; text = ""; fg = "green"; }
        { name = "terminal"; text = ""; fg = "green"; }
        { name = "test.js"; text = ""; fg = "yellow"; }
        { name = "test.jsx"; text = ""; fg = "yellow"; }
        { name = "test.ts"; text = ""; fg = "yellow"; }
        { name = "test.tsx"; text = ""; fg = "yellow"; }
        { name = "tex"; text = ""; fg = "blue"; }
        { name = "tf"; text = ""; fg = "magenta"; }
        { name = "tfvars"; text = ""; fg = "magenta"; }
        { name = "tgz"; text = ""; fg = "red"; }
        { name = "tmpl"; text = ""; fg = "cyan"; }
        { name = "tmux"; text = ""; fg = "green"; }
        { name = "toml"; text = ""; fg = "lightred"; }
        { name = "torrent"; text = ""; fg = "red"; }
        { name = "tres"; text = ""; fg = "blue"; }
        { name = "ts"; text = ""; fg = "blue"; }
        { name = "tscn"; text = ""; fg = "blue"; }
        { name = "tsconfig"; text = ""; fg = "blue"; }
        { name = "tsx"; text = ""; fg = "lightblue"; }
        { name = "ttf"; text = ""; fg = "cyan"; }
        { name = "twig"; text = ""; fg = "green"; }
        { name = "txt"; text = "󰈙"; fg = "white"; }
        { name = "txz"; text = ""; fg = "red"; }
        { name = "typ"; text = ""; fg = "lightblue"; }
        { name = "typoscript"; text = ""; fg = "lightred"; }
        { name = "ui"; text = ""; fg = "blue"; }
        { name = "v"; text = "󰍛"; fg = "lightblue"; }
        { name = "vala"; text = ""; fg = "cyan"; }
        { name = "vert"; text = ""; fg = "lightblue"; }
        { name = "vh"; text = "󰍛"; fg = "lightblue"; }
        { name = "vhd"; text = "󰍛"; fg = "lightblue"; }
        { name = "vhdl"; text = "󰍛"; fg = "lightblue"; }
        { name = "vi"; text = ""; fg = "green"; }
        { name = "vim"; text = ""; fg = "green"; }
        { name = "vsh"; text = ""; fg = "lightblue"; }
        { name = "vsix"; text = ""; fg = "magenta"; }
        { name = "vue"; text = ""; fg = "green"; }
        { name = "wasm"; text = ""; fg = "magenta"; }
        { name = "wav"; text = ""; fg = "yellow"; }
        { name = "webm"; text = ""; fg = "magenta"; }
        { name = "webmanifest"; text = ""; fg = "yellow"; }
        { name = "webp"; text = ""; fg = "magenta"; }
        { name = "webpack"; text = "󰜫"; fg = "lightblue"; }
        { name = "wma"; text = ""; fg = "yellow"; }
        { name = "wmv"; text = ""; fg = "magenta"; }
        { name = "woff"; text = ""; fg = "cyan"; }
        { name = "woff2"; text = ""; fg = "cyan"; }
        { name = "wrl"; text = "󰆧"; fg = "lightred"; }
        { name = "wrz"; text = "󰆧"; fg = "lightred"; }
        { name = "wv"; text = ""; fg = "yellow"; }
        { name = "wvc"; text = ""; fg = "yellow"; }
        { name = "x"; text = ""; fg = "gray"; }
        { name = "xaml"; text = "󰙳"; fg = "lightblue"; }
        { name = "xcf"; text = ""; fg = "magenta"; }
        { name = "xcplayground"; text = ""; fg = "red"; }
        { name = "xcstrings"; text = ""; fg = "lightblue"; }
        { name = "xls"; text = "󰈛"; fg = "green"; }
        { name = "xlsx"; text = "󰈛"; fg = "green"; }
        { name = "xm"; text = ""; fg = "gray"; }
        { name = "xml"; text = "󰗀"; fg = "lightblue"; }
        { name = "xpi"; text = ""; fg = "red"; }
        { name = "xslt"; text = "󰗀"; fg = "lightblue"; }
        { name = "xul"; text = ""; fg = "red"; }
        { name = "xz"; text = ""; fg = "red"; }
        { name = "yaml"; text = ""; fg = "red"; }
        { name = "yml"; text = ""; fg = "red"; }
        { name = "zig"; text = ""; fg = "red"; }
        { name = "zip"; text = ""; fg = "red"; }
        { name = "zsh"; text = ""; fg = "green"; }
        { name = "zst"; text = ""; fg = "red"; }
        { name = "🔥"; text = ""; fg = "lightred"; }
    ];

    conds = [
        { text = ""; "if" = "orphan"; fg = theme.filecolors.orphan; }
        { text = ""; "if" = "link"; fg = theme.filecolors.symlink; }
        { text = ""; "if" = "block"; }
        { text = ""; "if" = "char"; }
        { text = ""; "if" = "fifo"; }
        { text = ""; "if" = "sock"; }
        { text = ""; "if" = "sticky"; }
        { text = ""; "if" = "dummy"; }
        { text = ""; "if" = "dir & hovered"; fg = theme.filecolors.directory; }
        { text = ""; "if" = "dir"; fg = theme.filecolors.directory; }
        { text = ""; "if" = "exec"; fg = theme.filecolors.executable; }
        { text = ""; "if" = "!dir"; }
    ];

    filetypeRules =
        [ { url = "*"; } ]
        ++ map (e: { url = e.name; fg = e.fg; }) files
        ++ map (e: { url = "*.${e.name}"; fg = e.fg; }) exts
        ++ [
            { url = "*/"; fg = theme.filecolors.directory; }
            { url = "*"; is = "exec"; fg = theme.filecolors.executable; }
            { url = "*"; is = "link"; fg = theme.filecolors.symlink; }
            { url = "*"; is = "orphan"; fg = theme.filecolors.orphan; }
        ];
}